# Changes here will be overwritten by Copier
_commit: 6ffb43d
_src_path: https://github.com/oarepo/nrp-model-copier
base_model: ccmm
model_description: A minimal model allowing testing of various NRP InvenioRDM functionality.
model_human_name: Test-Record
